apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-bc-explorer
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-bc-explorer
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - persistentvolumeclaims
      - persistentvolumes
      - services
      - endpoints
      - events
      - configmaps
      - secrets
      - nodes
      - serviceaccounts
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "batch"
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - roles
      - clusterroles
      - rolebindings
      - clusterrolebindings
    verbs:
      - get
      - list
      - create
      - update
      - patch
      - watch
      - delete
      - deletecollection
      - bind
      - escalate
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - ibp.com
    resources:
      - ibpcas.ibp.com
      - ibppeers.ibp.com
      - ibporderers.ibp.com
      - ibpconsoles.ibp.com
      - organizations.ibp.com
      - federations.ibp.com
      - networks.ibp.com
      - proposals.ibp.com
      - votes.ibp.com
      - channels.ibp.com
      - chaincodebuilds.ibp.com
      - ibpcas
      - ibppeers
      - ibporderers
      - ibpconsoles
      - organizations
      - federations
      - networks
      - proposals
      - votes
      - channels
      - chaincodebuilds
      - ibpcas/finalizers
      - ibppeers/finalizers
      - ibporderers/finalizers
      - ibpconsoles/finalizers
      - organizations/finalizers
      - federations/finalizers
      - networks/finalizers
      - proposals/finalizers
      - votes/finalizers
      - channels/finalizers
      - chaincodebuilds/finalizers
      - ibpcas/status
      - ibppeers/status
      - ibporderers/status
      - ibpconsoles/status
      - organizations/status
      - federations/status
      - networks/status
      - proposals/status
      - votes/status
      - channels/status
      - chaincodebuilds/status
      - chaincodes
      - chaincodes/status
      - endorsepolicies
      - endorsepolicies/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - iam.tenxcloud.com
    resources:
      - users.iam.tenxcloud.com
      - users
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
      - taskruns
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-bc-explorer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-bc-explorer
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-bc-explorer
    namespace: {{ .Release.Namespace }}
