deployment:
  deployImage: hyperledgerk8s/bc-saas:6b0ed39

runtimeArgs:
  port: 9999
  addr: ""
  depositoryContract: depository
  db: pg
  # pg connection address
  dsn: "postgres://bestchains:Passw0rd!@bc-explorer-postgresql.baas-system.svc.cluster.local:5432/bc-saas?sslmode=disable"
  # or none
  authMethod: oidc

ingress:
  enable: false
  ingressClassName: portal-ingress
  ingressDomain: <replaced-ingress-nginx-ip>.nip.io
