{{- if .Values.oidcServer.enabled -}}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec: {{ .Values.issuerConfig.spec | toYaml | nindent 2 }}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: oidc-server-selfsigned-ca
  namespace: {{ .Release.Namespace }}
spec:
  isCA: true
  commonName: oidc-server-selfsigned-ca
  secretName: oidc-server-root-secret
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
  - digital signature
  - key encipherment
  - server auth
  ipAddresses: {{ toYaml .Values.oidcServer.cert.ipAddresses | nindent 4 }}
  dnsNames: {{ toYaml .Values.oidcServer.cert.dnsNames | nindent 4 }}
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
{{- end }}