apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-bc-saas
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-bc-saas
    spec:
      serviceAccountName: {{ .Release.Name }}
      volumes:
      - name: network-json
        secret:
          secretName: {{ .Release.Name }}
      - name: oidc-server-ca
        secret:
          defaultMode: 420
          items:
            - key: ca.crt
              path: ca.pem
          secretName: oidc-server-root-secret
      containers:
      - name: depository
        image: {{ .Values.deployment.deployImage }}
        command:
        - depository
        args:
        - -v=5
        - -profile=/opt/depository/network.json
        - -contract={{ .Values.runtimeArgs.depositoryContract }}
        - -db={{ .Values.runtimeArgs.db }}
        - -dsn={{ .Values.runtimeArgs.dsn }}
        - -auth={{ .Values.runtimeArgs.authMethod }}
        - -addr={{ .Values.runtimeArgs.addr }}:{{ .Values.runtimeArgs.port }}
        ports:
        - containerPort: {{ .Values.runtimeArgs.port }}
        env:
        - name: OIDC_CA_FILE
          value: "/etc/oidc/oidc-server/ca.pem"
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: oidc.client-id
              name: kube-oidc-proxy-config
        - name: OIDC_ISSUER_URL
          valueFrom:
            secretKeyRef:
              key: oidc.issuer-url
              name: kube-oidc-proxy-config
        - name: OIDC_USERNAME_CLAIM
          valueFrom:
            secretKeyRef:
              key: oidc.username-claim
              name: kube-oidc-proxy-config
        - name: OIDC_GROUPS_CLAIM
          valueFrom:
            secretKeyRef:
              key: oidc.group-claim
              name: kube-oidc-proxy-config
        volumeMounts:
        - name: network-json
          mountPath: /opt/depository
        - mountPath: /etc/oidc/oidc-server
          name: oidc-server-ca
          readOnly: true
